name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron:  '0 0 * * *' # Run every day at midnight.

jobs:

  functional:
    name: ${{ matrix.test-package }} / Phar ${{ matrix.use-phar }} / WP ${{ matrix.wp }} / PHP ${{ matrix.php }} / ${{ matrix.dbtype == 'sqlite' && 'SQLite' || 'MySQL' }}${{ matrix.object_cache == 'sqlite' && ' + Cache' || '' }}
    strategy:
      fail-fast: false
      matrix:
        php: ['7.2', '8.5']
        wp: ['latest', 'trunk']
        dbtype: ['mysql', 'sqlite']
        object_cache: ['none', 'sqlite']
        use-phar: [false, true]
        test-package:
          - wp-cli-bundle
          - wp-cli
          - ability-command
          - block-command
          - cache-command
          - checksum-command
          - config-command
          - core-command
          - cron-command
          - db-command
          - embed-command
          - entity-command
          - eval-command
          - export-command
          - extension-command
          - i18n-command
          - import-command
          - language-command
          - maintenance-mode-command
          - media-command
          - package-command
          - rewrite-command
          - role-command
          - scaffold-command
          - search-replace-command
          - server-command
          - shell-command
          - site-health-command
          - super-admin-command
          - widget-command
        exclude:
          # Object cache runs only on sqlite dbtype
          - dbtype: mysql
            object_cache: sqlite
            
          # A1: object_cache=sqlite only on PHP 8.5
          - php: '7.2'
            object_cache: sqlite
            
          # Phar usage match defaults 
          - use-phar: true
            wp: trunk
          - use-phar: false
            wp: latest
            
          # Limit ancient php on trunk
          - php: '7.2'
            wp: trunk
            
    uses: ./.github/workflows/reusable-testing.yml
    with:
      test-package: ${{ matrix.test-package }}
      php: ${{ matrix.php }}
      wp: ${{ matrix.wp }}
      dbtype: ${{ matrix.dbtype }}
      object_cache: ${{ matrix.object_cache }}
      use-phar: ${{ matrix.use-phar }}

